---
title: "Day 2 b Tasks"
author: "Carmen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse,palmerpenguins)
```

```{r}
# create an expression ----
fx <- expression(x^2)

# derive ----
df_dx <- D(expr = fx, name = "x")
df_dx

# evaluate ----
x <- 3
eval(df_dx)

#6
```

```{r}
pa <- expression(2 * (3 * a + 2)^4 - 5)
dp_da <- D(expr = pa, name = "a")
dp_da
a <- 1.2
eval(dp_da)

#4214.784
```

```{r}
library(palmerpenguins)
data(package='palmerpenguins')
penguins <- penguins
```

```{r}
data_range <- data.frame(x = c(30, 65))

ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm))+
  geom_point(aes(color = species))+
  xlab("Bill Length (mm)")+
  ylab("Bill Depth (mm)")+
  ggtitle("Bill Length vs. Depth")+
  theme(plot.title = element_text(hjust = 0.5))+
  facet_wrap(~island)
```

```{r}
ggplot(penguins, aes(x = flipper_length_mm, y = species))+
  geom_jitter()+
  xlab("Flipper Length (mm)")+
  ylab("Species")+
  ggtitle("Flipper Length by Species")+
  theme(plot.title = element_text(hjust = 0.5))
```


